apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: kube-system
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.17.4
    helm:
      valuesObject:
        k8sServiceHost: 10.10.10.10
        k8sServicePort: 6443
        ipv4:
          enabled: true
        ipv6:
          enabled: true
        l2announcements:
          enabled: true
        bpf:
          masquerade: true
        kubeProxyReplacement: true
        socketLB:
          hostNamespaceOnly: true
        extraConfig:
          enable-ipv6-ndp: "true"
          ipv6-mcast-device: "eno1"
          ipv6-service-range: "2001:cafe:43::/112"
        operator:
          replicas: 1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true