apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  project: default
  source:
    chart: discord-bot
    repoURL: https://xxczaki.github.io/charts/
    targetRevision: 0.16.59
    helm:
      valuesObject:
        secrets:
          token:
            name: secrets
            key: token
          sentryDsn:
            name: secrets
            key: sentryDsn
          spotifyClientSecret:
            name: secrets
            key: spotifyClientSecret
          openAiApiKey:
            name: secrets
            key: openAiApiKey

        env:
          clientId: "767113441718435850"
          playlistsChannelId: "1197942961695101090"
          botDebugChannelId: "1378037693094694922"
          ownerUserId: "349213466743013376"
          spotifyClientId: "cb115f7736cd45c9a7e8ae4555fa0f83"

        persistentVolumeClaim:
          storageClass: longhorn

        redis:
          architecture: standalone
          persistence:
            storageClass: longhorn
          auth:
            enabled: false

        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: discord-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
