apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
  namespace: openclaw-system
spec:
  project: default
  source:
    repoURL: https://github.com/xxczaki/argo-cd
    targetRevision: main
    path: openclaw
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openclaw-system
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /metadata/finalizers
        - /status
    - group: openclaw.rocks
      kind: OpenClawInstance
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
