---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openclaw-ts-auth
  namespace: openclaw-system
spec:
  encryptedData:
    authkey: AgBQLAMr+BSaIUwWmlb8oDcozbpGgb73+ExkRirC4fVJVlcCItNSkFTlaK8mg5D/EwdLIdUUr95RW0yc3AlwDuC/xOPz+RJYXdcSRT/VuNDUi2/UZZCaX75rjN7wWGAhDSRGNBmQEmY+dDHm06ehSAshIRDVhbDY1HrLTTz4VIJVGf47mo3mXoUD6X0An5v2EOBA0GSuVvO1W6ZjmYmSYH0qpNE2TPWJxd9kYmsMA5x7JzT+ZwAQNW6HNCRvtxqQ+1ubeWY5olEuygUpqqznNqVCtSe6H43UZHWmQr7m/PCf8h9j46Ywk+8vS3UtwL76/GOOGaT7zplTrisIkQx7LSdYQ+hifj2kB5Eve7qILUH6/Sn5Yc8KXY04zIGGyLPXegL7Imourkb2HjxP9OZ5WIwJlKMIGAHMZ5siSFra9EKYFlvQ4KtSRW1Z94gHaExG6adPwImXkPb8eza0AYG5lGI25KzM4ElJI/xRGRsiUbVbiRrTbFylmDTKc0CKFNMLR40gW5gvh5D3iUHu4VvD1RcFOAsi4lwrdvOzeGvPSd/2a1TrsIw06AW4xBJjLLKqLCOdpe/Fl5v0G1WyeOeUrVVktVoem68slTfnFPE+Ab4Ft+bMXMPvxlrZPoW/mcMHNS2FuQIcIyxRI4zegWy03X3xzj8CJb+8Si71hRcjksjEKrOsFcBS4j7VpXVmcytl1G2Si2nQdPcMhV+CDIDAlTnQNJhkizQv5zWtzqXsHuk5D9WlRu65NWXCm2cqqKYr1UtARTfUt9Q/rZYs8CyL
  template:
    metadata:
      creationTimestamp: null
      name: openclaw-ts-auth
      namespace: openclaw-system
    type: Opaque
