---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openclaw-ts-auth
  namespace: openclaw-system
spec:
  encryptedData:
    authkey: AgATbarOw6gYz7TVK/cvV/BODOX5Dy+nGt3orGEuyW77DXyZHsYUDR7+ySTWaxW7DFb3N2Z9q0aYGC87z2bhJaVQ3C7bWN7gnTTx07FtvCp4s572LqemjOFhoNFXSkfcjAMilqAMXskU3GNVW9YkX9tz1mXbPC4BnmaH7GjWviAIUo1gJIJbXNp11WPWc1O4uRcnG4xWeUKvXc2ckc0tqpvBuuH1QEIqAc9+HW6CZ6aT8Z0+9kEW2dUcHMFi/bEoGoemEVXEvzEI3l+onuS058RWG0AYfkh4yRWL1N/MdKZmVb1nyRtovtU2uSBMNiNTe0bGZx7rBQnXAva/VKErB9+EWTUxac3JNgcASJh76/z70yCdyTbCCX1CNDAIcmKu9i00yr35hxuu6lPsihy13C/s98VjbuFvU+L0sXzM0LP+yEzfxo7W2hhS1SFqNHAOI447VvBykmaLAP2JU8m38ozdcM2zUWnF1JCzKY7QWW7dYRSTDnSKF/91PbnCwsPepf/Lbdk5+4UPc78LHwISHN3IdOeq94egxDVoanL0K3OZXiXDGk5gJdRGM4jVjHhgUPz9qZ0wmmjcQas/7OwuI055pLDvTrbocJI7g6fbfu5cUgh0aMzmXrz98cr/bu24Huc92rOqDuKT8c1NUqot1GxzhMnRjTGT9v6hXKlEVBnxWSAns4zufkYtuL5wBPwl6jtSlVer5ZK242oYaT/i8xFoJOiijlFT8YgBeVc2zHa/cix7K1P93c9bV/pPP5C1K7ToZUwF+UueWC1BIDVOCg==
  template:
    metadata:
      creationTimestamp: null
      name: openclaw-ts-auth
      namespace: openclaw-system
    type: Opaque
