---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openclaw-ts-authkey
  namespace: openclaw-system
spec:
  encryptedData:
    TS_AUTHKEY: AgAkNJS6RPU8QIiS41BB1ROkQ5Zay8uH9WhSN8aHnuTrF+kMYlQcswTAo0y5qD9o8y/DEWf4gnwthHJ8z/VkXDuxoh9kU/bYZs5BvRy8RP+CP4KswaJUvrQCX73sHCz9C9trxqWJqINjxeY9mpmdUuoxYannxwZXS1xt7/SjVBgy4F6daKqJhGnX6iX6OIbGzo0XlkUMcf2rQxnGE7v9Jj3SwoKZKr1gZaxXaEZbcMgdDQYUDLhLeEWoc0YcZA4ZwAeiSMR9jXJ0c5AQgfym5XU7XKRxBgMwhmabXI7CBIPIyEHaVc0DJJodwmF5EG/NYz6ogL31X0+uUEjYvMX4SDLxSRcTOwyNNAm7tG8fm7uYhxXjCPl4cvrXWoRIVpLQDyd/xUAlnAs3xiDa3nIX5A5V7Kl5yt7RUsP6VQ90SH6wqn3GhfI4T+APftI+jlZBw8DPbC0WlUZpDK2fALJFXerbvTij8vGLAwJdHw6aljEcNGHwjjJAJl3EPFlZmLwo61AgoTAQaggVM3LgNZIf6CttSnT7myzQf/e9ThehPtdd86oB45g7tc8oL6izWBM/C1Z/OIAxjCexIW0SfSnHK1BODX0dlXtc1o5ydTvfYodmXV9OkLpTUnnoCtQAC1cciGF3soY47M86OC4oaAXJWLHYyrTZJi3Sm+QEbQqYJVgMoYkeDSyFvQJj0ZViXWC8jn4SieZ07LAz0ZThJ5/TftZM/jLhVKa1QIi6BM2kt+UsB6d3hX3mCcdP5mnyvBESjrILNpS50quXqgVl352pRQ==
  template:
    metadata:
      creationTimestamp: null
      name: openclaw-ts-authkey
      namespace: openclaw-system
    type: Opaque
