---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openclaw-ts-auth
  namespace: openclaw-system
spec:
  encryptedData:
    TS_AUTHKEY: AgCGWfbWzsZ4kepRgFyA0cn1YKEvpboSX9b5lr4W7WWz0pLKO6ZP3U80VImHUzY0pUXCfM4d9/+E77i6tPCTdlvp0IQTJUgKz/IDKXtx+EZHlnPCNp2hqvxb+ngCakzxhA6PV5iW8CrhW6FzLpWXlk9DnFZxv80lYpUyOt+ELLbXUveQaU010Jop0k7jEjD1fHGn0IKL/+4BHR8XMS994fU0M94fFW4RdnCUUyoL2o1dyiSTCokVSesvLgU4Q9oNMm07bzV4i6t7I1CSXm8kn0EC0DWIJg92jgg89eaxJaco0H5LBexpPhHW1NC7kD9zgeKcSwlFWuZ8ALZnj1+/W2m16k6701BM5HligTkUhswQUavkzDPQPcMtP3WqRzJ5lrbCkEYjrIp4LGJZTWvwU8XnWIh4GXs02fFADX6AqY4uSJpWFkuScJbYXFtdkMkh1npQ1UxZ3nb9U2kTVXYqU2CJd9RMRKogdJ95a++00mX9UBOwEeyCuZ27pyS7dcbXzAv+C7iyEU1Cf4zMMgdaKJJ5rdnsY62gVs4BE9rg8rzadKeGYSxS1cifrRH097YEIn9xTzaubRCKu/qQCKsAKkyq/p0lERRUtVSY5WYCEm6+j3H0tX5CIJW5CYCzY6xblQZXRONF8q4xhTU5yEHHwYILmwk3DFmtHWnSSfgqPacF463YiFAtVjXb6ENDswO2Ym1VzUAlPf/lR0UKd4zPWbd/Pbxr6aEI0F5q2GN/8jO9bOKhj3NDi9jMA4XXKuRZAxNhrXNUlCAG/ZVCL+WXSQ==
  template:
    metadata:
      creationTimestamp: null
      name: openclaw-ts-auth
      namespace: openclaw-system
    type: Opaque
