apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes
    targetRevision: 2.34.0
    helm:
      valuesObject:
        adlists:
          # Firebog Suspicious
          - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
          - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
          - https://v.firebog.net/hosts/static/w3kbl.txt
          # Firebog Advertising
          - https://adaway.org/hosts.txt
          - https://v.firebog.net/hosts/AdguardDNS.txt
          - https://v.firebog.net/hosts/Admiral.txt
          - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
          - https://v.firebog.net/hosts/Easylist.txt
          - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
          - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
          - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
          # Firebog Tracking & Telemetry
          - https://v.firebog.net/hosts/Easyprivacy.txt
          - https://v.firebog.net/hosts/Prigent-Ads.txt
          - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
          - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
          - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
          # Firebog Malicious
          - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
          - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
          - https://v.firebog.net/hosts/Prigent-Crypto.txt
          - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
          - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
          - https://phishing.army/download/phishing_army_blocklist_extended.txt
          - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
          - https://v.firebog.net/hosts/RPiList-Malware.txt
          - https://v.firebog.net/hosts/RPiList-Phishing.txt
          - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
          - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
          - https://urlhaus.abuse.ch/downloads/hostfile/
          # Misc
          - https://raw.githubusercontent.com/notracking/hosts-blocklists/master/adblock/adblock.txt
          - https://hole.cert.pl/domains/v2/domains.txt
          - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt
          - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/easylist_host.txt
          - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/easy_privacy_host.txt
          - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/gambling-hosts.txt
          - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/adguard_host.txt
          - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/Ad_filter_list_by_Disconnect.txt
          - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/adguard_crypto_host.txt
          - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/adguard_host.txt
          - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/adguard_mobile_host.txt
          - https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/adservers.txt

        whitelist:
          - t.co
          - marketingplatform.google.com
          - (\.|^)railway\.com$ # has to be manually changed to be considered a RegExp in the dashboard, unfortunately

        admin:
          enabled: false

        # serviceWeb:
        #   https:
        #     port: 55443
        #   http:
        #     port: 55080
        
        ingress:
          enabled: true
          ingressClassName: tailscale
          hosts:
            - pi-hole
          tls:
            - hosts:
              - pi-hole

        podDnsConfig:
          enabled: false

        dualStack:
          enabled: true

        extraEnvVars:
          TZ: "Europe/Warsaw"
          FTLCONF_dns_listeningMode: SINGLE

        DNS1: 1.1.1.1
        DNS2: 2606:4700:4700::1111

        dnsmasq:
          customSettings:
            - dns-forward-max=150
            - min-cache-ttl=3600

        serviceDns:
          mixedService: true
          type: LoadBalancer
          annotations:
            tailscale.com/expose: "true"
      
        probes:
          liveness:
            initialDelaySeconds: 300
          readiness:
            initialDelaySeconds: 300

        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pi-hole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true