---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCtxdHp+ZREUTYo+r7aqUkeCDj/GutgISOu1sumvGIv5Oj3UDQWgcHZcdXcDOOxVSM9Q3whljnag+p5EZF+02nF9S3UZhdc0O/81N6Y5MhG942o1jf3ElVqZfzKZQnjXL5QSCDCxYOLHDiictqmG/ZOtC5nwYXABro7tno7L3iUJ201ucpqQQAuLe1OMkixV9EQc32ZqgusqL9FWw3i0gHB3JoJ1aZGrlQG+/5Z3QbFhUrJ1y90fZ0Ndmi9soxxVIPDIO7QugnM089HIUchaIWvgSTNH+WwReL5EXAWf+l162X8MGuMBb140YxEd43yg7uDMLwGXom6sNy8WOO0oUHuKhx6GTBZwAO860+7Ard2PTVbfgFglhglow/o76dUpVM4G5l/5sg2RjzNxr09Y6enwgxrXVMepFfdIl/KQrsi803qNw965D9MM+/PAkQAKgFNiTAeuRbhj5l7eIG/nZPkl2x8PwpiJTGP/76vwmw2g9nRedbgG4WZHhqoHlMk8K085eeBsW6FvUWnu28vuc/aZcp6cS/WnmhzHrbhfOLp6CLFkerrUP2aSECqp8nYeZ+5ZgfQCoEkNjw2vVVWVr6ndeqTSMU+VXwQVrOPBu84OYDZpkPlp6yZPG4u27BUMHpioIvuh+hw9jEXH/RioxEq04PNnb3jy91mmLnARchzDSHuFlSKZf7k7jBOUAieTbcQAWsU9774igVFH5qLChot6w==
    client_secret: AgA+NW2a8XZQFeRTfSkdt5N4Jl+q45lpuB6GwgJhfNkXSUWhML2nbtNHila69bxT6tF4+3oZgz79nNfmU6SVNA8Vzh35wUpT3spc0cdjpw3xtfGpyMo1tqwv3Q7xrkBr3t33nFamm4kBU2rAR9mfsGkOMuG5fMCeg8+bgG635IQOTDLIBgrpYT2Zt57IsudtholEbl3aeCcHqIkhaGQY86rHEilEVHCO7t1BWjZWTp5yzskoHx49baa0CSfL71c5pLxk2dRg7BL8LJCe/1rEWk43EKBaX9p+l1u7o1shSHrnjTHzN0lCJf5fCkAxZdk3ZDrq9mtd+NmIthcXYW9eEV12XaHvsMbNR3Ax0TocinGIidSFy39AZo+ihWmw34Li0KAeRNbGx1H5mN0PUpDjYTELueEcHbsIJLDFRq4tzIDdUaMYRVBDW4n2mz45QJ66PUfJKa7l38JUtDy0icEtrtXbJ0No2FtA4ys73yfXW5KRfzxwsnMfOzfVaH5gZltbOA2fs2/we1hg7e/iB/iR4UNZncGoqryzfmkfRDjn2tqFLlFnnjlE42aV57Fg3GUVTzYQERXb8s/rmj5FwH0wW2w5xBwb4+xIhYn2+s8IH4dtobLaH0HvHcqh90N276rzFbNX0tGYDjdcOuqOWBS7nGd3QvFYXBKVWROGsfrw2UWiNVVACbR4rKUIMmjHPSU6HUuU4q7S/CxIBFLXJDsfKUUq45lVKKEDepr0QOfeVS3+lfGf9fv96+WRhKl8Hr+xvyh2hrCOMnR5Ci/MNK+HRp8b
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
