---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBlfLcvCI7KZTDT5St8D36SLRKd3pZyDvGxF8v/gmL1JVJoamQp//9D5py2SquvGYs7qXxSeYaSqfp+dLrWd6DEmyUH6iOQKdv6BcqhOYUNnbzM4agUci+se4VbhcuD4qsSpDQF4yOG+KWbmgDK5pZZbxQnfSPng2TnnfOV8POAZtow5E4AVh9DlvWxOW797zxs2VRoxycuGXE24/VhJaEh5ws8s9J635Q5rD0mpGJZqvFT42Sz2Cwjb+1XT+12LepHEmK1clgwhdupHvx74fGUlWo9nwKSfe1S2obZvmyBdHDH3tRXHi9rlErEOgmwHs5F0u4prqtT55HbHImsre3+mw0gbM+k19TFdc877lZEpIiaHXB5NUca370XKyg0X5xcYUjyyWDT0Qz682OuYlvAXcvhqhei8df9kxHsG3eHCv0j63yqimUFN5atEJTc1gArRWq0bv/EOy/TiL38GM474cFk+c4Zrmyoh6KGINzK6063jmcyZZrMJWlxNnw0+2XB7JAkfhcll53r2NK+cej0Vd2CwG87XsLcK4hAasDnOsDQ9SDRH4Hi+RrcHHiLnfE89meocskY7351DEHHu6cPaHl5q5PgxznQjq4bBfXz6xafttaJtbHNHVIcPZou/o8bXJ9q6iQyIXGao700oW6JPpT1ZKhc0nrhh179s6BxPG+2QhBZ9DLYhNzNucNz4NzC1bypCZ/6nPXMD4+Tm+0R9g==
    client_secret: AgBUIJAT8e6FDs9wcqUaifS047avnMUsr8Kgxd4ulVmAFTAvYDutazHPzT24McxbKpk7RjemJPBtOCZ92ys2deBouQ/rDr+z63dBIyGypn0zdU5Hfev2JPK+zzIVnWGZ9iygzI8iJGP41vwDNFEAC6qw5Y9R9XzRw3550EO3yKmrPqm3Kz9kxXNnXT+l1qXUii7KJk5MavgKYzDbDsTOOqeghhQZDFsckMgGa7Ulzmlq3AzEfbfJAMBqspk8ncsQakW6iAkzlzqhBlJz++L6tYH3XwSV0QMDWHy/0778YnRYkF7E41vvHdpwvHcSk8qSv8P89eB98QXboH5KPw1j5pum0uyFqXdKCVhX0f/UXAwe9IZtbv6Tb17bTlvLLouuWyLNE2ayMlSOlTUWFJFA5gAdkHVHmCmcdk2g9OlDjcksmYQos9jmZLAoy0EduUyfw3ia5ZuLRXP2D3iUXWnK4RXFGTqKIZUZfdTMcYGnv2ui28dZ5nE7CnhPzOYik8aNAXzju1UVH9CKJW3GK0fE5VfflyeFvfIz9552fXBk+bIGX99YmV4Cit2Dpo6/MXr1QI8uGK1ivf6l0+ZgJUZdn+e3rgUmWypXafYQO3iU/Sa1dcfEDZAl5cd4ko7SXoza2zhYcxrKpSSqyfknb6u9ZDGMCcljz/H41gpGGeb9boUxAmDwm52XGqKHSC+2KWrHEQbaXgS9xmF2s+ptplJ+5xZgqxc8S2iNcVXoDd5tX29pIHpw+yPuLipCcThucFz+OZJwxD+VG91F++AlzKkM73oL
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
