---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openclaw-api-keys
  namespace: openclaw-system
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgAAdk5k8Wrvm2GAVmLMPmoNEt9GoTxFWUAHwYMb6ozMkM7UOYl7o2EZlFjdLDpM5OmTgUIubfWL+nYUE7ku4chtwbh86YHo2vvwVFqiwUYShDRESyVTP7fTzX+yCD2yJZZNjfYCpXunhwbcY/kV1VfqdxLFzvrIkpM5aR0xvTBAp2m34/a5R2AoOz7R+iOq17WlMpw/Qb81oZyUVBJGUm3lP7AUVjRhoTTDLl99wgF10FD0VkP5fu7i35hbV/ScJHjNjL3Iw0lVJkkK3F4N/DvMvCfXST4iqtJO1rFmHVVBqryfBa9cH3/MqNgzr8zgW1qYUq9dipvK5h2ZphPZ7FaM8pF6JO/u/rLQon7aFsdt2AgmWaHATMZn0JyXWulXdzSY1k5owJT9XxB0kFk6KuSc8RWoHbae1eVgu8otONf5R8joOs1CaKWPD4UirNfJqTHbE+KI9RMJgOm+3G1nYkP7yb52OQa+toalQ0rK09xFezX6qyW0d3U7RRlZQcJ+Y6HQrUVltux0N0IPh0EhjSlqPhVzJEoCJPMvKsETvsDCU7YJZwIyj1Koq/2dQCm0v8KdIcxYpGCUGrjD2gLR16ugZW4inXvatThOWA1EyxJomlpglx/sirWFBen8c0UIuOVBt6m3xqDVLjdwxcnS8grZSwlAVLrMyAg/ssr4Vim+Oc3KDGYksoHfTVksfgycJBma+/dmiRFI8z5gdjXaM+b65Ph6gqelP3BW5fEHMnPfIztuWsSZA2HZYU5Uwxzv3Xu3HzPlef6aGYKNSJdCB32P0DVJnGFt27qoI8rPByKpCTxQbMnZalUnxWzWEACy5+4j4n+GTFrOTo+sTEk=
  template:
    metadata:
      creationTimestamp: null
      name: openclaw-api-keys
      namespace: openclaw-system
    type: Opaque
